### PR TITLE
Include Java 9 classes into coverage report

### PR DESCRIPTION
**Pull request by Godin**
This solves problem described in https://github.com/jacoco/jacoco/issues/965

### CODE REVIEW

**Comment by amaembo** [comment]
Wow! Thank you very much! I completely forgot that every Maven problem can be fixed with a bit of Ant :-) Really appreciate your PR.

**Comment by Godin** [comment]
> Wow! Thank you very much!

@amaembo you're welcome! :heart:

> I completely forgot that every Maven problem can be fixed with a bit of Ant :-)

so true 🤣 anyway I still have to answer on https://github.com/jacoco/jacoco/issues/965

And note BTW seems that Coveralls doesn't fully/properly support such layout for multirelease JARs - it displays only `src/main/java/one/util/streamex/VerSpec.java` but not `src/main/java-mr/9/one/util/streamex/VerSpec.java` , while now `target/site/jacoco/index.html` displays both because they are declared in two different `<group>`s , `jacoco-maven-plugin:report` unlike `jacoco-maven-plugin:report-aggregate` defines single group, so same source/class name within same module is also not supported.

BTW Have you thought about replacing Maven by Gradle? 😉

> Really appreciate your PR.

Let's keep going - #204 , #205 :wink:

**Comment by amaembo** [comment]
> And note BTW seems that Coveralls doesn't fully/properly support such layout for multirelease JARs

In my case, I can live with this. I decided to keep a bare minimum of code in the classes with the same FQN, so it's always covered. Everything else should have different FQN.

> BTW Have you thought about replacing Maven by Gradle? 😉

I'm a complete newbie in Gradle, so migration would take a considerable amount of time, especially taking into account that I do some non-trivial things in Maven, so unlikely I can just copy-paste some snippets from SO to make everything working. Currently, the benefit is not quite clear to me.

**Comment by Godin** [comment]
@amaembo makes sense,
however exactly what is not so trivial with Maven might become trivial,
but you're right this will require Gradle knowledge,
so consider maybe one day when you'll get tired of tricks for Maven :wink:

**Comment by amaembo** [comment]
@Godin btw see https://habr.com/ru/post/472312/

**Comment by Godin** [comment]
@amaembo nice 👍

However don't know why you wrote

> Я использую JaCoCo, и если ему ничего не сказать, то второй прогон просто **затрёт результаты первого**.

Because it is exactly opposite - by default agent appends to the existing file. See [`append` parameter of agent](https://www.jacoco.org/jacoco/trunk/doc/agent.html) and [corresponding `append` parameter of `jacoco-maven-plugin:prepare-agent`](https://www.jacoco.org/jacoco/trunk/doc/prepare-agent-mojo.html).

So unless there is some other reason, you can get rid of multiple `exec` files - #206 :wink:

**Comment by Godin** [comment]
Here is proof that file `target/jacoco.exec` after execution of `mvn clean package` contains both versions of class `one/util/streamex/VerSpec`:

```
$ java -jar ./jacoco-0.8.5/lib/jacococli.jar classinfo target/classes/one/util/streamex/VerSpec.class
  INST   BRAN   LINE   METH   CXTY   ELEMENT
     5      0      1      1      1   class 0xeaf239c6ccdf4975 one/util/streamex/VerSpec

$ java -jar ./jacoco-0.8.5/lib/jacococli.jar classinfo target/classes-9/one/util/streamex/VerSpec.class
  INST   BRAN   LINE   METH   CXTY   ELEMENT
     5      0      1      1      1   class 0x1457506964186199 one/util/streamex/VerSpec

$ java -jar ./jacoco-0.8.5/lib/jacococli.jar execinfo target/jacoco.exec | grep VerSpec
1457506964186199    1 of   1   one/util/streamex/VerSpec
eaf239c6ccdf4975    1 of   1   one/util/streamex/VerSpec
```

**Pull request merged**
