### PR TITLE
least/greatest improvement: Limiter

### PR DESCRIPTION
**Pull request by ArthurGazizov**
I really liked your implementation of the Limiter, just added small optimization. When current Limiter is in initial state and we want to putAll items from other limiter, we can do system array copy if space is enough. Result will be the same as if just call put method for each element

### CODE REVIEW

**Comment by ArthurGazizov** [comment]
I really liked your implementation of the Limiter, just added small optimization. When current Limiter is in `initial` state and we want to putAll items from other limiter, we can do system array copy if space is enough. Result will be the same as if just call `put` method for each element

**Comment by ArthurGazizov** [comment]
@amaembo could you please help me a little bit with error, seems to me it doesn’t relate to commit🙂

`Error:  Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project streamex: Build error: Either repository token or service with job id must be defined -> [Help 1]`

**Comment by amaembo** [comment]
Yes, it doesn't. Please ignore it.

**Comment by amaembo** [comment]
Thanks.

**Pull request merged**
