### PR TITLE
StreamExTest fail fix

### PR DESCRIPTION
**Pull request by AntonyKapustin**

### CODE REVIEW

**Comment by amaembo** [comment]
Could you please be more verbose under which conditions StreamEx build fails (JDK version/vendor/patch/OS/etc.?)

**Comment by amaembo** [comment]
I fixed build (for some reason Travis did not notify me that it was failed) and refactored these tests to extract the repeating code to the `TestHelpers.checkIllegalStateException` (see commit 0e07d404e59977dbbf578810fbdda0e4a1bf6a18). Could you please update your patch on top of these changes and provide more descriptive commit message and/or comment in the code why this change is necessary (under which circumstances the test fails currently)? Thanks.

**Comment by AntonyKapustin** [comment]
fails two tests: StreamExTest -> testToSortedMap, testToMap. You expect message "Duplicate entry for key '2' (attempt to merge values 'bb' and 'dd')", but sometimes message received "java.lang.IllegalStateException: Duplicate entry for key '2' (attempt to merge values 'bb' and 'dd')" - Test fails - but test still actual(all works fine). I added a new message(with java.lang.IllegalStateException) in the expected messages. P.S. sorry for my english.

**Comment by amaembo** [comment]
So on your system these tests fail not every time, but only sometimes? I never saw these tests failed, neither on local system, nor on Travis reports. Still it would be nice to see which JDK version/os/vendor are you using (what is printed in `java -version` output?).

**Comment by AntonyKapustin** [comment]
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

**Comment by AntonyKapustin** [comment]
You have cycle, in some iteration message "Duplicate entry for key '2' (attempt to merge values 'bb' and 'dd')" in others "java.lang.IllegalStateException: Duplicate entry for key '2' (attempt to merge values 'bb' and 'dd')". But if condition -  only for "Duplicate entry for key '2' (attempt to merge values 'bb' and 'dd')".

**Comment by amaembo** [comment]
Ok, please update the pull-request on top of the latest changes (modify checkIllegalStateException method instead) and I will merge it.

**Comment by AntonyKapustin** [comment]
Ok.

**Comment by AntonyKapustin** [comment]
0278c10 ready.

**Pull request closed without merging**
