### PR TITLE
StreamEx#without(Collection)

### PR DESCRIPTION
**Pull request by valery1707**
Also i can add methods `StreamEx#without(T...)`, `IntStreamEx#without(int...)` and `LongStreamEx#without(long...)`

### CODE REVIEW

**Comment by amaembo** [comment]
Thank you for the pull request. Unfortunately in general I don't like this change. Writing `remove(collection::contains)` is not much longer than writing `without(collection)`. Saving 9 chars does not worth adding a new method. On the other hand calling `remove(collection::contains)` user will explicitly know that the `contains` method is used, so if it's slow (has linear complexity, for example), then the overall process will be slow, and it's user fault not to use faster collection. Using the proposed `without(collection)` it's less evident how we define whether element is inside the collection, so the user might blame the library for the slowness instead of switching to faster collection.

Also special handling of null argument is actually against the fail-fast concept. Currently library throws NPE every time when null collection or null array argument is supplied (e.g. `StreamEx.of(collection)`, `StreamEx.prepend(collection)` and so on). This is conscious solution: you should not have null in array or collection variable (use empty array or `Collections.emptyList()` instead). Throwing NPE as soon as possible is better than simply accepting potentially dangerous value. JDK also works like this (for example, `Arrays.asList(null)` or `Arrays.stream((int[])null)` will throw NPE). The StreamEx philosophy here follows the JDK philosophy: be strict, don't accept any garbage as the input.

Checking specially for `isEmpty()` may optimize the corner case, but I don't think it has really big value. Also such optimization makes early-binding for empty collection, but late-binding for non-empty collection which is dubious. I know that I do the same thing in `append(Collection)` and `cross(Collection)`, but probably that was not the best idea.

Finally your proposed change may break the backward compatibility on the source level with existing code (you actually changed the existing tests to make your feature working!).

So in conclusion I must decline this pull request.

As for `without(T...)`, `without(int...)`, `without(long...)`: these things I like more. I thought about adding such feature as well. The main problem here is the computational difficulty. The simplest solution is to perform the linear scan of the supplied array for every stream element which will make the overall difficulty as `O(n*m)` where `n` is the number of stream elements and `m` is the array length. Having such method with might encourage users to use it instead of manually converting the input to the efficient data structure. For example, use might have long `String[]` array. Currently user might write:

    String[] toExclude = ...
    Set<String> excludeSet = new HashSet<>(Arrays.asList(toExclude));
    result = StreamEx.of(something).remove(excludeSet::contains).toList();

After the proposed change user will be able to write:

    String[] toExclude = ...
    StreamEx.of(something).without(toExclude).toList();

While this is shorter, it would be less efficient. Or should we create a `HashSet` internally (making the method early-binding)? This way we should require the consistent `hashCode/equals` implementation (and `compareTo` if it's comparable as `HashSet` may use it!). Or should we create a `HashSet` only if array size is bigger than some threshold? And what about primitive case? If user has some library with primitive sets (like Trove or Koloboke), he may create an efficient set and use it with `remove`. The StreamEx library cannot use such collections (and it probably would be too much to implement `IntSet`/`LongSet` internally, though this could be discussed). So should we use `HashSet<Integer>` and `HashSet<Long>` boxed sets in these cases? Such questions should be addressed.

**Comment by valery1707** [comment]
Thanks for explanation

**Comment by amaembo** [comment]
In general if you want to develop some new features, it's probably better to discuss them in this issue tracker first so you will not do some extra work if I'm not going to accept such feature. Anyways thank you for the interest to my library.

I opened Issue #41 for the further discussion on `without(T...)` methods family.

**Comment by amaembo** [comment]
I thought about `without(T...)` again. If you want, you may implement it and send the pull request. It will still break the source compatibility with `without(null)` case, but it's acceptable change (after all if you want to remove nulls, there's already `nonNull()` method). The new `without(T...)` method must throw NPE if called with null-array (like `without((T[])null)`). You may optimize empty array case as it's impossible to modify empty array after creation, so no early-binding issue will arise. It's acceptable to make linear search implementation in current version, though this must be explicitly stated in the method documentation (probably with the proposed work-around like replacing `without(array)` with `remove(StreamEx.of(array).toSet()::contains)` for big arrays). It's desired that `without(a,b,c)` works not slower than `without(a).without(b).without(c)`. Please notify me if you are going to implement this.

**Comment by valery1707** [comment]
I would like to implement this method, but i can do this only at monday evening

**Comment by amaembo** [comment]
As Monday evening passed long ago I'll implement the #41 issue by myself :-)

**Comment by valery1707** [comment]
Sorry for long delay :(

**Pull request closed without merging**
